#sonar-project.properties
# Le dice a SonarCloud cómo analizar tu proyecto
sonar.projectKey=mariaquispecc/falabella/settings/secrets/actions/
sonar.organization=mariaquispecc
# Nombre del proyecto que aparece en el dashboard de SonarCloud
sonar.projectName=falabella
# Qué archivos analizar
sonar.sources=src
sonar.tests=tests
# Excluir node_modules y archivos de configuración
sonar.exclusions=node_modules/**,coverage/**
# Indicar dónde está el reporte de cobertura de Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info
# Encoding
sonar.sourceEncoding=UTF-8