name: CI Jest (Unit & API Tests)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-unit:
    name: Ejecutar suite Jest
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24' # Puedes cambiarla por tu versión de Node local
        cache: 'npm'

    - name: Instalar dependencias
      run: npm install

      # Ejecutar tests Y verificar umbrales de cobertura
    # Si la cobertura baja del 70%, este paso falla → pipeline en rojo
    - name: Tests + Quality Gate de cobertura
      run: npm run test/unit:coverage
    # Subir el reporte HTML como artefacto descargable
    - name: Subir reporte de cobertura
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report
        path: coverage/lcov-report/
        retention-days: 7